apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
resources:
- ../../../../istio/oidc-authservice/overlays/application
configMapGenerator:
- name: oidc-authservice-parameters
  behavior: merge
  literals:
  - client_id=
  - oidc_provider=https://federatesys.intuit.com
  - oidc_redirect_uri=https://kubeflow.mlpdev.a.intuit.com/login/oidc
  - oidc_auth_url=https://federatesys.intuit.com/as/authorization.oauth2
  - application_secret=
  - skip_auth_uri=/as
  - namespace=istio-system
  - userid-header=kubeflow-userid
  - userid-prefix=
